package chrome

import (
	"strings"

	"github.com/chromedp/chromedp/device"
)

func UserDevice(name string) (device.Info, bool) {
	ret, ok := _devices[strings.ToLower(name)]
	return ret, ok
}

// TODO improve this to use generates
var _devices = map[string]device.Info{
	strings.ToLower(device.BlackberryPlayBook.Device().Name):          device.BlackberryPlayBook.Device(),
	strings.ToLower(device.BlackberryPlayBooklandscape.Device().Name): device.BlackberryPlayBooklandscape.Device(),
	strings.ToLower(device.BlackBerryZ30.Device().Name):               device.BlackBerryZ30.Device(),
	strings.ToLower(device.BlackBerryZ30landscape.Device().Name):      device.BlackBerryZ30landscape.Device(),
	strings.ToLower(device.GalaxyNote3.Device().Name):                 device.GalaxyNote3.Device(),
	strings.ToLower(device.GalaxyNote3landscape.Device().Name):        device.GalaxyNote3landscape.Device(),
	strings.ToLower(device.GalaxyNoteII.Device().Name):                device.GalaxyNoteII.Device(),
	strings.ToLower(device.GalaxyNoteIIlandscape.Device().Name):       device.GalaxyNoteIIlandscape.Device(),
	strings.ToLower(device.GalaxySIII.Device().Name):                  device.GalaxySIII.Device(),
	strings.ToLower(device.GalaxySIIIlandscape.Device().Name):         device.GalaxySIIIlandscape.Device(),
	strings.ToLower(device.GalaxyS5.Device().Name):                    device.GalaxyS5.Device(),
	strings.ToLower(device.GalaxyS5landscape.Device().Name):           device.GalaxyS5landscape.Device(),
	strings.ToLower(device.GalaxyS8.Device().Name):                    device.GalaxyS8.Device(),
	strings.ToLower(device.GalaxyS8landscape.Device().Name):           device.GalaxyS8landscape.Device(),
	strings.ToLower(device.GalaxyS9.Device().Name):                    device.GalaxyS9.Device(),
	strings.ToLower(device.GalaxyS9landscape.Device().Name):           device.GalaxyS9landscape.Device(),
	strings.ToLower(device.GalaxyTabS4.Device().Name):                 device.GalaxyTabS4.Device(),
	strings.ToLower(device.GalaxyTabS4landscape.Device().Name):        device.GalaxyTabS4landscape.Device(),
	strings.ToLower(device.IPad.Device().Name):                        device.IPad.Device(),
	strings.ToLower(device.IPadlandscape.Device().Name):               device.IPadlandscape.Device(),
	strings.ToLower(device.IPadgen6.Device().Name):                    device.IPadgen6.Device(),
	strings.ToLower(device.IPadgen6landscape.Device().Name):           device.IPadgen6landscape.Device(),
	strings.ToLower(device.IPadgen7.Device().Name):                    device.IPadgen7.Device(),
	strings.ToLower(device.IPadgen7landscape.Device().Name):           device.IPadgen7landscape.Device(),
	strings.ToLower(device.IPadMini.Device().Name):                    device.IPadMini.Device(),
	strings.ToLower(device.IPadMinilandscape.Device().Name):           device.IPadMinilandscape.Device(),
	strings.ToLower(device.IPadPro.Device().Name):                     device.IPadPro.Device(),
	strings.ToLower(device.IPadProlandscape.Device().Name):            device.IPadProlandscape.Device(),
	strings.ToLower(device.IPadPro11.Device().Name):                   device.IPadPro11.Device(),
	strings.ToLower(device.IPadPro11landscape.Device().Name):          device.IPadPro11landscape.Device(),
	strings.ToLower(device.IPhone4.Device().Name):                     device.IPhone4.Device(),
	strings.ToLower(device.IPhone4landscape.Device().Name):            device.IPhone4landscape.Device(),
	strings.ToLower(device.IPhone5.Device().Name):                     device.IPhone5.Device(),
	strings.ToLower(device.IPhone5landscape.Device().Name):            device.IPhone5landscape.Device(),
	strings.ToLower(device.IPhone6.Device().Name):                     device.IPhone6.Device(),
	strings.ToLower(device.IPhone6landscape.Device().Name):            device.IPhone6landscape.Device(),
	strings.ToLower(device.IPhone6Plus.Device().Name):                 device.IPhone6Plus.Device(),
	strings.ToLower(device.IPhone6Pluslandscape.Device().Name):        device.IPhone6Pluslandscape.Device(),
	strings.ToLower(device.IPhone7.Device().Name):                     device.IPhone7.Device(),
	strings.ToLower(device.IPhone7landscape.Device().Name):            device.IPhone7landscape.Device(),
	strings.ToLower(device.IPhone7Plus.Device().Name):                 device.IPhone7Plus.Device(),
	strings.ToLower(device.IPhone7Pluslandscape.Device().Name):        device.IPhone7Pluslandscape.Device(),
	strings.ToLower(device.IPhone8.Device().Name):                     device.IPhone8.Device(),
	strings.ToLower(device.IPhone8landscape.Device().Name):            device.IPhone8landscape.Device(),
	strings.ToLower(device.IPhone8Plus.Device().Name):                 device.IPhone8Plus.Device(),
	strings.ToLower(device.IPhone8Pluslandscape.Device().Name):        device.IPhone8Pluslandscape.Device(),
	strings.ToLower(device.IPhoneSE.Device().Name):                    device.IPhoneSE.Device(),
	strings.ToLower(device.IPhoneSElandscape.Device().Name):           device.IPhoneSElandscape.Device(),
	strings.ToLower(device.IPhoneX.Device().Name):                     device.IPhoneX.Device(),
	strings.ToLower(device.IPhoneXlandscape.Device().Name):            device.IPhoneXlandscape.Device(),
	strings.ToLower(device.IPhoneXR.Device().Name):                    device.IPhoneXR.Device(),
	strings.ToLower(device.IPhoneXRlandscape.Device().Name):           device.IPhoneXRlandscape.Device(),
	strings.ToLower(device.IPhone11.Device().Name):                    device.IPhone11.Device(),
	strings.ToLower(device.IPhone11landscape.Device().Name):           device.IPhone11landscape.Device(),
	strings.ToLower(device.IPhone11Pro.Device().Name):                 device.IPhone11Pro.Device(),
	strings.ToLower(device.IPhone11Prolandscape.Device().Name):        device.IPhone11Prolandscape.Device(),
	strings.ToLower(device.IPhone11ProMax.Device().Name):              device.IPhone11ProMax.Device(),
	strings.ToLower(device.IPhone11ProMaxlandscape.Device().Name):     device.IPhone11ProMaxlandscape.Device(),
	strings.ToLower(device.IPhone12.Device().Name):                    device.IPhone12.Device(),
	strings.ToLower(device.IPhone12landscape.Device().Name):           device.IPhone12landscape.Device(),
	strings.ToLower(device.IPhone12Pro.Device().Name):                 device.IPhone12Pro.Device(),
	strings.ToLower(device.IPhone12Prolandscape.Device().Name):        device.IPhone12Prolandscape.Device(),
	strings.ToLower(device.IPhone12ProMax.Device().Name):              device.IPhone12ProMax.Device(),
	strings.ToLower(device.IPhone12ProMaxlandscape.Device().Name):     device.IPhone12ProMaxlandscape.Device(),
	strings.ToLower(device.IPhone12Mini.Device().Name):                device.IPhone12Mini.Device(),
	strings.ToLower(device.IPhone12Minilandscape.Device().Name):       device.IPhone12Minilandscape.Device(),
	strings.ToLower(device.IPhone13.Device().Name):                    device.IPhone13.Device(),
	strings.ToLower(device.IPhone13landscape.Device().Name):           device.IPhone13landscape.Device(),
	strings.ToLower(device.IPhone13Pro.Device().Name):                 device.IPhone13Pro.Device(),
	strings.ToLower(device.IPhone13Prolandscape.Device().Name):        device.IPhone13Prolandscape.Device(),
	strings.ToLower(device.IPhone13ProMax.Device().Name):              device.IPhone13ProMax.Device(),
	strings.ToLower(device.IPhone13ProMaxlandscape.Device().Name):     device.IPhone13ProMaxlandscape.Device(),
	strings.ToLower(device.IPhone13Mini.Device().Name):                device.IPhone13Mini.Device(),
	strings.ToLower(device.IPhone13Minilandscape.Device().Name):       device.IPhone13Minilandscape.Device(),
	strings.ToLower(device.JioPhone2.Device().Name):                   device.JioPhone2.Device(),
	strings.ToLower(device.JioPhone2landscape.Device().Name):          device.JioPhone2landscape.Device(),
	strings.ToLower(device.KindleFireHDX.Device().Name):               device.KindleFireHDX.Device(),
	strings.ToLower(device.KindleFireHDXlandscape.Device().Name):      device.KindleFireHDXlandscape.Device(),
	strings.ToLower(device.LGOptimusL70.Device().Name):                device.LGOptimusL70.Device(),
	strings.ToLower(device.LGOptimusL70landscape.Device().Name):       device.LGOptimusL70landscape.Device(),
	strings.ToLower(device.MicrosoftLumia550.Device().Name):           device.MicrosoftLumia550.Device(),
	strings.ToLower(device.MicrosoftLumia950.Device().Name):           device.MicrosoftLumia950.Device(),
	strings.ToLower(device.MicrosoftLumia950landscape.Device().Name):  device.MicrosoftLumia950landscape.Device(),
	strings.ToLower(device.Nexus10.Device().Name):                     device.Nexus10.Device(),
	strings.ToLower(device.Nexus10landscape.Device().Name):            device.Nexus10landscape.Device(),
	strings.ToLower(device.Nexus4.Device().Name):                      device.Nexus4.Device(),
	strings.ToLower(device.Nexus4landscape.Device().Name):             device.Nexus4landscape.Device(),
	strings.ToLower(device.Nexus5.Device().Name):                      device.Nexus5.Device(),
	strings.ToLower(device.Nexus5landscape.Device().Name):             device.Nexus5landscape.Device(),
	strings.ToLower(device.Nexus5X.Device().Name):                     device.Nexus5X.Device(),
	strings.ToLower(device.Nexus5Xlandscape.Device().Name):            device.Nexus5Xlandscape.Device(),
	strings.ToLower(device.Nexus6.Device().Name):                      device.Nexus6.Device(),
	strings.ToLower(device.Nexus6landscape.Device().Name):             device.Nexus6landscape.Device(),
	strings.ToLower(device.Nexus6P.Device().Name):                     device.Nexus6P.Device(),
	strings.ToLower(device.Nexus6Plandscape.Device().Name):            device.Nexus6Plandscape.Device(),
	strings.ToLower(device.Nexus7.Device().Name):                      device.Nexus7.Device(),
	strings.ToLower(device.Nexus7landscape.Device().Name):             device.Nexus7landscape.Device(),
	strings.ToLower(device.NokiaLumia520.Device().Name):               device.NokiaLumia520.Device(),
	strings.ToLower(device.NokiaLumia520landscape.Device().Name):      device.NokiaLumia520landscape.Device(),
	strings.ToLower(device.NokiaN9.Device().Name):                     device.NokiaN9.Device(),
	strings.ToLower(device.NokiaN9landscape.Device().Name):            device.NokiaN9landscape.Device(),
	strings.ToLower(device.Pixel2.Device().Name):                      device.Pixel2.Device(),
	strings.ToLower(device.Pixel2landscape.Device().Name):             device.Pixel2landscape.Device(),
	strings.ToLower(device.Pixel2XL.Device().Name):                    device.Pixel2XL.Device(),
	strings.ToLower(device.Pixel2XLlandscape.Device().Name):           device.Pixel2XLlandscape.Device(),
	strings.ToLower(device.Pixel3.Device().Name):                      device.Pixel3.Device(),
	strings.ToLower(device.Pixel3landscape.Device().Name):             device.Pixel3landscape.Device(),
	strings.ToLower(device.Pixel4.Device().Name):                      device.Pixel4.Device(),
	strings.ToLower(device.Pixel4landscape.Device().Name):             device.Pixel4landscape.Device(),
	strings.ToLower(device.Pixel4a5G.Device().Name):                   device.Pixel4a5G.Device(),
	strings.ToLower(device.Pixel4a5Glandscape.Device().Name):          device.Pixel4a5Glandscape.Device(),
	strings.ToLower(device.Pixel5.Device().Name):                      device.Pixel5.Device(),
	strings.ToLower(device.Pixel5landscape.Device().Name):             device.Pixel5landscape.Device(),
	strings.ToLower(device.MotoG4.Device().Name):                      device.MotoG4.Device(),
	strings.ToLower(device.MotoG4landscape.Device().Name):             device.MotoG4landscape.Device(),
}
