// Code generated by go generate; DO NOT EDIT.
//go:generate go run all_gen.go

package all

import (
	// plugins
	_ "github.com/OutOfBedlam/tine/plugins/args"
	_ "github.com/OutOfBedlam/tine/plugins/base"
	_ "github.com/OutOfBedlam/tine/plugins/chrome"
	_ "github.com/OutOfBedlam/tine/plugins/excel"
	_ "github.com/OutOfBedlam/tine/plugins/exec"
	_ "github.com/OutOfBedlam/tine/plugins/expr"
	_ "github.com/OutOfBedlam/tine/plugins/http"
	_ "github.com/OutOfBedlam/tine/plugins/image"
	_ "github.com/OutOfBedlam/tine/plugins/mqtt"
	_ "github.com/OutOfBedlam/tine/plugins/nats"
	_ "github.com/OutOfBedlam/tine/plugins/ollama"
	_ "github.com/OutOfBedlam/tine/plugins/psutil"
	_ "github.com/OutOfBedlam/tine/plugins/screenshot"
	_ "github.com/OutOfBedlam/tine/plugins/sqlite"
	_ "github.com/OutOfBedlam/tine/plugins/syslog"
	_ "github.com/OutOfBedlam/tine/plugins/telegram"
	_ "github.com/OutOfBedlam/tine/plugins/template"
)

const A = ""
