name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    # - name: install librrd-dev
    #   if: startsWith(matrix.platform, 'macos')
    #   run: brew install rrdtool
    # - name: install librrd-dev
    #   if: startsWith(matrix.platform, 'ubuntu')
    #   run: sudo apt-get install -y librrd-dev

    - name: Build
      run: go run magefiles/mage.go build package

    - name: Test
      run: go run magefiles/mage.go test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Release files
      uses: svenstaro/upload-release-action@2.7.0
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        repo_token: ${{ secrets.GIT_PASS }}
        file: dist/tine-v*.zip
        repo_name: OutOfBedlam/tine
        prerelease: true
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
