# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    ## for x/rrd plugins and test cases
    - name: install librrd-dev
      run: sudo apt-get install -y librrd-dev

    - name: Build
      run: go run magefiles/mage.go build

    - name: Test
      run: go test -v ./...
